# Generated by Django 2.0.6 on 2018-06-10 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('video_id', models.CharField(default='', max_length=11)),
                ('start', models.PositiveSmallIntegerField(default=0)),
                ('end', models.PositiveSmallIntegerField(default=0)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('artists', models.ManyToManyField(to='content.Artist')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
