# Generated by Django 2.0.6 on 2018-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='prompts',
            field=models.ManyToManyField(related_name='artists', to='content.Prompt'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='keywords',
            field=models.CharField(default='', max_length=256),
        ),
    ]
