# Generated by Django 2.0.6 on 2018-06-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180612_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='prompts',
        ),
        migrations.AddField(
            model_name='prompt',
            name='artists',
            field=models.ManyToManyField(related_name='prompts', to='content.Artist'),
        ),
    ]
