# Generated by Django 2.0.6 on 2018-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180612_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='artists',
            field=models.ManyToManyField(related_name='prompts', related_query_name='prompt', to='content.Artist'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
