# Generated by Django 2.0.6 on 2018-06-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180612_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=128)),
                ('phrase', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('sponsor',),
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='keyphrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.KeyPhrase'),
        ),
    ]
