# Generated by Django 2.0.6 on 2018-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180613_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='keyphrase',
            unique_together={('sponsor', 'phrase')},
        ),
    ]
